---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Missing values

```{r, include=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
source("srcs/helpers.R")
load(file = "data/processing/imdb_sample.RData")
load(file = "data/processing/imdb.RData")

```

## Missing value recognition

- First we need to understand how the NA is encoded in the dataset. So we calculate the most common value among each colomns:

```{r}
imdb_sample %>%
  mutate_all(~as.character(.)) %>%
  pivot_longer(1:ncol(.)) %>%
  group_by(name, value) %>%
  summarise(nunique = n()) %>%
  group_by(name) %>%
  arrange(-nunique) %>%
  slice(1:15)
```

- Apparently, `\N` is likely to be a tag for missing value.

```{r}
SIGN_of_MISSING <- c('\\N', "", "[]", "	#N/A", "#N/A")
```



## Missing plot

```{r,fig.width=11,fig.height=8}
imdb %>%
  mutate_all( ~ifelse(. %in% SIGN_of_MISSING, NA, .) ) %>%
  mutate_at("isAdult", ~ifelse(. %in% c('0', '1'), ., NA) ) %>%
  plot_missing(percent = T, long_axis = T)
```

- 有的超过60%的rows都出现了 endYear pattern的缺失，但是没关系



